tinyMCE.addI18n('ru.emotions_dlg',{
title:"Вставить смайл",
desc:"Смайлы",
cool:"Круто",
cry:"Плачет",
embarassed:"Смущенный",
foot_in_mouth:"Косноязычный",
frown:"Нахмуренный",
innocent:"Святой",
kiss:"Поцелуй",
laughing:"Смеётся",
money_mouth:"Корыстный",
sealed:"Молчит",
smile:"Улыбка",
surprised:"Удевлённый",
tongue_out:"Высунул язык",
undecided:"Нерешительный",
wink:"Подмигивающий",
yell:"Кричит"
});