tinyMCE.addI18n('ru.advanced_dlg',{
about_title:"Подробнее о TinyMCE",
about_general:"Подробности",
about_help:"Справка",
about_license:"Лицензия",
about_plugins:"Плагтны",
about_plugin:"Плаин",
about_author:"Разработчик",
about_version:"Версия",
about_loaded:"Загруженные плагины",
anchor_title:"Вставить/редактировая якорь",
anchor_name:"Имя якоря",
code_title:"Редактор исходного кода HTML",
code_wordwrap:"Word wrap",
colorpicker_title:"Выбрать цвет",
colorpicker_picker_tab:"Спектр",
colorpicker_picker_title:"Спектр цветов",
colorpicker_palette_tab:"Палитра",
colorpicker_palette_title:"Цвета палитры",
colorpicker_named_tab:"Проименованные",
colorpicker_template_tab:"Шаблон",
colorpicker_named_title:"Проименованные цвета",
colorpicker_template_title:"Цвета шаблона",
colorpicker_color:"Цвет:",
colorpicker_name:"Имя:",
charmap_title:"Выбрать специальный символ",
image_title:"Вставить/редактировать изображение",
image_src:"URL изображения",
image_alt:"Описание изображения",
image_list:"Image list",
image_border:"Рамка",
image_dimensions:"Размеры",
image_vspace:"Отступ по вертикали",
image_hspace:"Отступ по горизонтали",
image_align:"Выравнивание",
image_align_baseline:"Базовая строка",
image_align_top:"Верх",
image_align_middle:"Центр",
image_align_bottom:"Низ",
image_align_texttop:"Верх текста",
image_align_textbottom:"Низ текста",
image_align_left:"Слева",
image_align_right:"Справа",
link_title:"Вставить/редактировать ссвлку",
link_url:"Ссылка URL",
link_target:"Цель",
link_target_same:"Открыть ссылку в текущем окне",
link_target_blank:"Открыть ссылку в новом окне",
link_titlefield:"Заголовок",
link_is_email:"URL, котрый вы ввели выглядит как e-mail адрес, вы хотите добавить необходимый префикс отправки e-mail сообщения?",
link_is_external:"URL, котрый вы ввели выглядит как внешняя ссылка, вы хотите добавить необходимый префикс: http://?",
link_list:"Список ссылок"
});